// This file is autogenerated

import aipng from './assets/images/ai.png';
import bookpng from './assets/images/book.png';
import boxpng from './assets/images/box.png';
import breadpng from './assets/images/bread.png';
import clawclosedpng from './assets/images/claw-closed.png';
import clawopenpng from './assets/images/claw-open.png';
import clockpng from './assets/images/clock.png';
import couchpng from './assets/images/couch.png';
import downpng from './assets/images/down.png';
import glassespng from './assets/images/glasses.png';
import headphonespng from './assets/images/headphones.png';
import leftpng from './assets/images/left.png';
import logopng from './assets/images/logo.png';
import pausepng from './assets/images/pause.png';
import remotecontrolpng from './assets/images/remote-control.png';
import rightpng from './assets/images/right.png';
import runningshoepng from './assets/images/running-shoe.png';
import teddybearpng from './assets/images/teddy-bear.png';
import tiepng from './assets/images/tie.png';
import tophatpng from './assets/images/top-hat.png';
import tvpng from './assets/images/tv.png';
import uppng from './assets/images/up.png';

function preload() {
	return Promise.all([
		(() => new Promise((resolve) => {const aipngImage = new Image();aipngImage.onload = resolve;aipngImage.src = aipng;}))(),
		(() => new Promise((resolve) => {const bookpngImage = new Image();bookpngImage.onload = resolve;bookpngImage.src = bookpng;}))(),
		(() => new Promise((resolve) => {const boxpngImage = new Image();boxpngImage.onload = resolve;boxpngImage.src = boxpng;}))(),
		(() => new Promise((resolve) => {const breadpngImage = new Image();breadpngImage.onload = resolve;breadpngImage.src = breadpng;}))(),
		(() => new Promise((resolve) => {const clawclosedpngImage = new Image();clawclosedpngImage.onload = resolve;clawclosedpngImage.src = clawclosedpng;}))(),
		(() => new Promise((resolve) => {const clawopenpngImage = new Image();clawopenpngImage.onload = resolve;clawopenpngImage.src = clawopenpng;}))(),
		(() => new Promise((resolve) => {const clockpngImage = new Image();clockpngImage.onload = resolve;clockpngImage.src = clockpng;}))(),
		(() => new Promise((resolve) => {const couchpngImage = new Image();couchpngImage.onload = resolve;couchpngImage.src = couchpng;}))(),
		(() => new Promise((resolve) => {const downpngImage = new Image();downpngImage.onload = resolve;downpngImage.src = downpng;}))(),
		(() => new Promise((resolve) => {const glassespngImage = new Image();glassespngImage.onload = resolve;glassespngImage.src = glassespng;}))(),
		(() => new Promise((resolve) => {const headphonespngImage = new Image();headphonespngImage.onload = resolve;headphonespngImage.src = headphonespng;}))(),
		(() => new Promise((resolve) => {const leftpngImage = new Image();leftpngImage.onload = resolve;leftpngImage.src = leftpng;}))(),
		(() => new Promise((resolve) => {const logopngImage = new Image();logopngImage.onload = resolve;logopngImage.src = logopng;}))(),
		(() => new Promise((resolve) => {const pausepngImage = new Image();pausepngImage.onload = resolve;pausepngImage.src = pausepng;}))(),
		(() => new Promise((resolve) => {const remotecontrolpngImage = new Image();remotecontrolpngImage.onload = resolve;remotecontrolpngImage.src = remotecontrolpng;}))(),
		(() => new Promise((resolve) => {const rightpngImage = new Image();rightpngImage.onload = resolve;rightpngImage.src = rightpng;}))(),
		(() => new Promise((resolve) => {const runningshoepngImage = new Image();runningshoepngImage.onload = resolve;runningshoepngImage.src = runningshoepng;}))(),
		(() => new Promise((resolve) => {const teddybearpngImage = new Image();teddybearpngImage.onload = resolve;teddybearpngImage.src = teddybearpng;}))(),
		(() => new Promise((resolve) => {const tiepngImage = new Image();tiepngImage.onload = resolve;tiepngImage.src = tiepng;}))(),
		(() => new Promise((resolve) => {const tophatpngImage = new Image();tophatpngImage.onload = resolve;tophatpngImage.src = tophatpng;}))(),
		(() => new Promise((resolve) => {const tvpngImage = new Image();tvpngImage.onload = resolve;tvpngImage.src = tvpng;}))(),
		(() => new Promise((resolve) => {const uppngImage = new Image();uppngImage.onload = resolve;uppngImage.src = uppng;}))(),
	]);
}

export default preload;